modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="metro_radiation"
version="1.0.0"
displayName="Metro Radiation"
description="Basic radiation system by biome"

[[dependencies.metro_radiation]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.metro_radiation]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"